# Generated by Django 5.2.7 on 2025-10-20 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_studentprofile_delete_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='skill',
            name='availability',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
