# Generated by Django 5.2.7 on 2025-10-21 12:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_report'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Report',
        ),
    ]
